version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR in $AWS_DEFAULT_REGION...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 715841334721.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t python-api .
      - docker tag python-api:latest 715841334721.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/python-api:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 715841334721.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/python-api:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"python-api-container","imageUri":"%s"}]' 715841334721.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/python-api:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
